package org.javalite.activeweb.controllers;

import org.javalite.activeweb.AppController;

/**
 * This controller is to be subclassed by an application developer in case
 * he/she wants to handle all system exceptions. For example add this to the
 * RouteConfig class:
 * <p/>
 * <pre>
 * <code>public void init(AppContext appContext) {
 *     routeError().to(SystemErrorController.class).action("error");
 * }
 * </code>
 * </pre>
 *
 * This way, you can have a full control of any system exception coming out
 * of the framework.
 *
 */
public class AbstractSystemErrorController extends AppController {

    private Throwable throwable;

    /**
     * @return an instance of Throwable that was generated by the framework or the application.
     */
    public Throwable getThrowable() {
        return throwable;
    }

    public void setThrowable(Throwable throwable) {
        this.throwable = throwable;
    }
}
