/**
 *
Copyright 2012 Kalyan Mulampaka

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */
package activejdbc.codegen;

import java.io.File;
import org.apache.commons.lang.StringUtils;
import org.apache.commons.lang.WordUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utility class used in code generation
 * 
 * @author Kalyan Mulampaka
 * 
 */
public class CodeGenUtil
{

	final static Logger logger = LoggerFactory.getLogger(CodeGenUtil.class);

	public CodeGenUtil ()
	{

	}

	/**
	 * Returns the java bean style name for the input database column name.
	 * assumes database column name words are separated by underscores ('_'). If
	 * there are no underscores the input string is returned as is. e.g
	 * created_at will return createdAt
	 * 
	 * @param name
	 * @return
	 */
	public static String normalize (String name)
	{
		StringBuilder strBuf = new StringBuilder("");
		// e,g created_at
		// should become createdAt

		char[] delimiter =
		{ '_' };
		if (name.indexOf("_") != -1)
		{
			name = WordUtils.capitalize(name, delimiter); // CreatedAt
			name = StringUtils.uncapitalize(name); // createdAt
			name = StringUtils.replace(name, "_", "");
		}
		strBuf.append(name);
		return strBuf.toString();
	}

	/**
	 * Creates the package folder structure if already not present
	 * 
	 * @param packageName
	 *            String
	 * @throws Exception
	 */
	public static void createPackage (String rootFolderPath, String packageName) throws Exception
	{
		String path = "";
		if (StringUtils.isNotBlank(packageName))
		{
			path = StringUtils.replace(packageName, ".", "/");
			if (StringUtils.isNotBlank(rootFolderPath))
			{
				logger.info("Generated code will be in folder:{}", rootFolderPath);
				path = rootFolderPath + "/" + path;
			}
			File file = new File(path);
			if (!file.exists())
			{
				file.mkdirs();
				logger.info("Package structure created:" + path);
			}
		}
	}

	public static StringBuffer generateComment ()
	{
		StringBuffer strBuf = new StringBuffer("");
		strBuf.append("\t/**\n");
		strBuf.append("\t * This method is generated by ActiveJDBC code generator.\n");
		strBuf.append("\t *\n");
		strBuf.append("\t * @generatedcode\n");
		strBuf.append("\t */\n");
		return strBuf;
	}

}